development:
  enable_star: true
  min_infix_len: 2
  mem_limit: 128M
  morphology: stem_en
  indexed_models:
    - Product
    - Category
test:
  enable_star: true
  min_infix_len: 2
production:
  enable_star: true
  min_infix_len: 2
  mem_limit: 256M
  morphology: stem_en
